#!/usr/bin/env bash
# Verify the PUBLISHED packages, end to end, from a throwaway directory.
#
#     bash test/verify-published.sh
#
# Nothing local is used: every artifact is downloaded from registry.npmjs.org, so this checks
# what a stranger actually gets — not what is sitting in this working tree. Each check prints
# PASS/FAIL with what it observed, and the two that matter most are deliberately adversarial:
# `apply` must REFUSE a half-filled project half, and `check` must CATCH an edited CORE block.
# A suite that only ever confirms the happy path cannot tell you it is working.
set -uo pipefail

ROOT="$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/brain-kit-verify.$$")"
trap 'rm -rf "$ROOT"' EXIT
mkdir -p "$ROOT/fleet/myapp/.claude"; cd "$ROOT"
echo "verifying the PUBLISHED packages in $ROOT"

PASS=0; FAIL=0; SKIP=0
ok()   { echo "  PASS  $1"; PASS=$((PASS+1)); }
bad()  { echo "  FAIL  $1"; echo "        observed: $2"; FAIL=$((FAIL+1)); }
skip() { echo "  SKIP  $1 ($2)"; SKIP=$((SKIP+1)); }
hdr()  { echo; echo "── $1 ─────────────────────────────────────────"; }

hdr "1. install all three from the registry (nothing local)"
cd "$ROOT"
npm init -y >/dev/null 2>&1
if npm install agent-brain-kit claude-brain-kit @alexadamis/brain-kit >/dev/null 2>&1; then
  ok "npm install of all three succeeded"
else
  bad "npm install" "install failed"; exit 1
fi

IMPL="$ROOT/node_modules/agent-brain-kit"
# Shell-only: `node -p require(<abs path>)` is not portable here, because a POSIX temp path
# (mktemp on Git Bash) is not a path the Windows node binary can resolve.
V=$(grep -m1 '"version"' "$IMPL/package.json" | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*//')
[ -n "$V" ] && ok "agent-brain-kit resolved at v$V" || bad "version read" "empty"

hdr "2. the package SHIPPED what it promises"
for f in kit.mjs CLAUDE.core.md BRAIN_DISCIPLINE.md README.md LICENSE \
         templates/BRAIN.template.md templates/CLAUDE.project.template.md \
         sync-hooks.sh verify-kit.sh; do
  [ -f "$IMPL/$f" ] && ok "ships $f" || bad "ships $f" "missing from published tarball"
done
HOOKS=$(ls "$IMPL/hooks" 2>/dev/null | wc -l)
[ "$HOOKS" -ge 7 ] && ok "ships $HOOKS hooks" || bad "hooks" "only $HOOKS found"

hdr "3. every shipped shell script is syntactically valid"
BADSH=0
for f in "$IMPL"/*.sh "$IMPL"/hooks/*.sh; do
  bash -n "$f" 2>/dev/null || { echo "        bad syntax: $f"; BADSH=$((BADSH+1)); }
done
[ "$BADSH" -eq 0 ] && ok "all shell scripts parse" || bad "shell syntax" "$BADSH file(s) failed bash -n"

hdr "4. lifecycle: init"
cd "$ROOT"
OUT=$(node "$IMPL/kit.mjs" init myapp --fleet-root "$ROOT/fleet" 2>&1)
echo "$OUT" | grep -q "CLAUDE.project.md" && ok "init proposed CLAUDE.project.md" || bad "init" "$OUT"
[ -f "$ROOT/fleet/myapp/.claude/CLAUDE.project.md" ] && ok "CLAUDE.project.md written" || bad "project half" "not written"
[ ! -f "$ROOT/fleet/myapp/.claude/CLAUDE.md" ] && ok "init did NOT touch CLAUDE.md (as documented)" || bad "init safety" "CLAUDE.md was written by init"

hdr "5. apply REFUSES while placeholders remain (the safety gate)"
OUT=$(node "$IMPL/kit.mjs" apply myapp --fleet-root "$ROOT/fleet" 2>&1)
echo "$OUT" | grep -qi "REFUSING" && ok "apply refused unfilled placeholders" || bad "placeholder gate" "$OUT"
[ ! -f "$ROOT/fleet/myapp/.claude/CLAUDE.md" ] && ok "nothing written on refusal" || bad "refusal" "CLAUDE.md written anyway"

hdr "6. lifecycle: apply after filling"
P="$ROOT/fleet/myapp/.claude/CLAUDE.project.md"
sed -i 's/PLACEHOLDER/filled/g' "$P"
sed -i -E 's@<[^>!/][^>]{2,}>@filled@g' "$P"
OUT=$(node "$IMPL/kit.mjs" apply myapp --fleet-root "$ROOT/fleet" 2>&1)
echo "$OUT" | grep -q "applied" && ok "apply composed the file" || bad "apply" "$OUT"
C="$ROOT/fleet/myapp/.claude/CLAUDE.md"
[ -f "$C" ] && ok "CLAUDE.md exists" || bad "CLAUDE.md" "missing"

CORE=$(grep -c "KIT:CORE:BEGIN" "$C" 2>/dev/null || echo 0)
PROJ=$(grep -c "KIT:PROJECT:BEGIN" "$C" 2>/dev/null || echo 0)
[ "$CORE" -eq 8 ] && ok "8 CORE blocks composed" || bad "CORE blocks" "got $CORE, want 8"
[ "$PROJ" -eq 4 ] && ok "4 PROJECT blocks composed" || bad "PROJECT blocks" "got $PROJ, want 4"
grep -q "GENERATED by brain-kit/kit.mjs" "$C" && ok "banner warns against hand-editing" || bad "banner" "missing"
grep -q "PROJECT CONSTITUTION — myapp" "$C" && ok "titled for the right repo" || bad "title" "wrong repo name"

hdr "7. lifecycle: check reports canonical"
OUT=$(node "$IMPL/kit.mjs" check myapp --fleet-root "$ROOT/fleet" 2>&1)
echo "$OUT" | grep -q "core is canonical" && ok "check says core is canonical" || bad "check" "$OUT"

hdr "8. check DETECTS tampering (not a vacuous pass)"
sed -i 's/READ FIRST/READ LATER/' "$C"
OUT=$(node "$IMPL/kit.mjs" check myapp --fleet-root "$ROOT/fleet" 2>&1)
if echo "$OUT" | grep -qi "canonical"; then
  bad "tamper detection" "check still said canonical after editing a CORE block"
else
  ok "check caught an edited CORE block"
fi
node "$IMPL/kit.mjs" apply myapp --fleet-root "$ROOT/fleet" >/dev/null 2>&1

hdr "9. the BRAIN template is usable"
cp "$IMPL/templates/BRAIN.template.md" "$ROOT/fleet/myapp/BRAIN.md"
for s in "1. WHAT THIS IS" "2. ARCHITECTURE" "3. CURRENT STATE" "4. OUTSTANDING" \
         "5. GOTCHAS" "6. CHANGELOG" "7. DECISIONS" "8. TELEMETRY"; do
  grep -q "$s" "$ROOT/fleet/myapp/BRAIN.md" && ok "BRAIN has §$s" || bad "BRAIN §$s" "missing"
done

hdr "10. sync-hooks distributes into a real repo"
cd "$ROOT/fleet/myapp" && git init -q 2>/dev/null; mkdir -p .claude/hooks
cd "$ROOT"
OUT=$(bash "$IMPL/sync-hooks.sh" "$ROOT/fleet" --dry-run 2>&1)
echo "$OUT" | grep -qE "would change" && ok "sync-hooks dry-run ran" || bad "sync-hooks" "$OUT"
N=$(echo "$OUT" | grep -c "ADD " || echo 0)
[ "$N" -ge 7 ] && ok "would install $N hooks (not a vacuous 0)" || bad "hook count" "only $N"
OUT=$(bash "$IMPL/sync-hooks.sh" "$ROOT/fleet" 2>&1)
LANDED=$(ls "$ROOT/fleet/myapp/.claude/hooks" 2>/dev/null | wc -l)
[ "$LANDED" -ge 7 ] && ok "$LANDED hooks actually landed on disk" || bad "hooks on disk" "$LANDED"

hdr "11. both alias packages resolve to the same implementation"
for A in claude-brain-kit "@alexadamis/brain-kit"; do
  B="$ROOT/node_modules/$A/bin.mjs"
  if [ -f "$B" ]; then
    mkdir -p "$ROOT/fleet/alias-$RANDOM/.claude" 2>/dev/null
    D="aliascheck$RANDOM"; mkdir -p "$ROOT/fleet/$D/.claude"
    OUT=$(cd "$ROOT" && node "$B" init "$D" --fleet-root "$ROOT/fleet" 2>&1)
    echo "$OUT" | grep -q "CLAUDE.project.md" && ok "$A runs the shared implementation" || bad "$A" "$OUT"
  else
    bad "$A" "bin.mjs not installed"
  fi
done

hdr "RESULT"
echo "  PASS=$PASS  FAIL=$FAIL  SKIP=$SKIP"
[ "$FAIL" -eq 0 ] && echo "  ✅ ALL CHECKS PASSED against the PUBLISHED packages" || echo "  ❌ $FAIL CHECK(S) FAILED"
exit $FAIL
